// Generated by ts-to-zod
import { z } from 'zod';

export const gendersSchema = z.object({
  male: z.object({
    label: z.string(),
  }),
  female: z.object({
    label: z.string(),
  }),
  unspecified: z.object({
    label: z.string(),
  }),
});

export type Gender = (typeof GendersEnum.options)[number];

export const GendersEnum = z.enum(['male', 'female', 'unspecified']);

// This is a roundabout way of ensuring the GendersEnum values match the keys of `gendersSchema`.
// There's not really a better way to do this that I know of
type TypeTest1 =
  (typeof GendersEnum.options)[number] extends (
    keyof z.infer<typeof gendersSchema>
  ) ?
    true
  : false;

const _pass: TypeTest1 = true;

export const accountSchema = z.object({
  phone: z
    .object({
      callingCode: z.preprocess(String, z.string()),
      digitRange: z.array(z.number()).optional(),
      format: z.string().optional(),
    })
    .optional(),
  registration: z.object({
    emailUpdatesDefaultUnchecked: z.boolean().optional(),
    genderAllowUnselected: z.boolean(),
    genders: gendersSchema.optional(),
    oauths: z.array(z.string()).optional().nullable(),
    showLoginInNav: z.boolean(),
    usePostal: z.boolean().optional(),
    zipKeyboard: z.string().optional().nullable(),
    zipRegex: z.string().optional().nullable(),
    zipStringLength: z.number().optional().nullable(),
  }),
});

export type Account = z.infer<typeof accountSchema>;
