// Generated by ts-to-zod
import { z } from 'zod';

export const featuresSchema = z.object({
  lyricsLengthMaxDeviation: z.number(),
  newPodcastPlaybackOrder: z.boolean(),
  podcastTritonTokenEnabled: z.boolean(),
  showHomepageHero: z.boolean(),
  showMarketingBanner: z.boolean(),
  showPodcastSearch: z.boolean(),
  showPodcastTranscriptions: z.boolean(),
  showRankers: z.boolean(),
  showUserEducationTour: z.boolean(),
  useAmpTranscription: z.boolean(),
  playbackBufferTimeout: z.number(),
  socialShareEnabled: z.boolean(),
  playlistPredictability: z.boolean(),
});

export type Features = z.infer<typeof featuresSchema>;
