// Generated by ts-to-zod
import { z } from 'zod';

export const gFKSensicSchema = z.object({
  enabled: z.boolean(),
  script: z.string(),
});

export type GFKSensic = z.infer<typeof gFKSensicSchema>;
