// Generated by ts-to-zod
import { z } from 'zod';

export const outbrainSchema = z.object({
  enabled: z.boolean(),
  pixelId: z.string(),
});

export type Outbrain = z.infer<typeof outbrainSchema>;
