// Generated by ts-to-zod
import { z } from 'zod';

export const permutiveSchema = z.object({
  apiKey: z.string(),
  projectId: z.string(),
});

export type Permutive = z.infer<typeof permutiveSchema>;
